# Generated by Django 4.2 on 2023-05-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesional',
            old_name='email',
            new_name='mail',
        ),
    ]
