# Generated by Django 4.2 on 2023-05-18 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_email_profesional_mail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='fechaturno',
        ),
    ]
