# Generated by Django 4.2 on 2023-05-18 00:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_remove_turno_fechaturno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fechaturno',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
